// tonight/src/lib/components/navigation/DatePicker.svelte
<!-- DatePicker component that user interacts with to choose date of data to display. -->
<script lang="ts">
	import CalendarIcon from 'svelte-radix/Calendar.svelte';
	import { DateFormatter, type DateValue, getLocalTimeZone } from '@internationalized/date';
	import { cn } from '$lib/utils.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Calendar } from '$lib/components/ui/calendar/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';
	import { afterUpdate } from 'svelte';
	import { dateToYMD } from '$lib/utils.js';
	import { date } from '$lib/stores.js';

	const df = new DateFormatter('en-US', {
		dateStyle: 'long'
	});

	/* Update the URL with the selected date. */
	afterUpdate(() => {
		const url = new URL(window.location.href);
		url.searchParams.set('date', dateToYMD($date.toDate(getLocalTimeZone())));
		window.history.pushState({}, '', url.toString());
	});
</script>

<Popover.Root>
	<Popover.Trigger asChild let:builder>
		<Button
			variant="outline"
			class={cn('w-[240px] justify-start text-left font-normal', !$date && 'text-muted-foreground')}
			builders={[builder]}
		>
			<CalendarIcon class="mr-2 h-4 w-4" />
			{$date ? df.format($date.toDate(getLocalTimeZone())) : df.format(new Date())}
		</Button>
	</Popover.Trigger>
	<Popover.Content class="w-auto p-0" align="start">
		<Calendar bind:value={$date} />
	</Popover.Content>
</Popover.Root>

<slot></slot>

// tonight/src/components/DatePicker.tsx
"use client";

import * as React from "react";
import { CalendarIcon } from "@radix-ui/react-icons";
import { format } from "date-fns";
import { cn } from "@/utils/shadcn";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { useRouter, usePathname } from "next/navigation";
import { dateToYMD } from "@/utils/date";

export default function DatePicker() {
  const [date, setDate] = React.useState<Date>();
  const pathname = usePathname();
  const router = useRouter();

  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button
          variant={"outline"}
          className={cn(
            "w-[240px] justify-start text-left font-normal",
            !date && "text-muted-foreground"
          )}
        >
          <CalendarIcon className="mr-2 h-4 w-4" />
          {date ? format(date, "PPP") : <span>Pick a date</span>}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-auto p-0" align="start">
        <Calendar
          mode="single"
          selected={date}
          onSelect={(date) => {
            setDate(date);
            router.push(`${pathname}?date=${dateToYMD(date)}`);
          }}
          initialFocus
        />
      </PopoverContent>
    </Popover>
  );
}
